### ISSUE TITLE
安装 Python 库依赖报错

### ISSUE THREAD

**Issue by lyric2018** [jumpserver/docs#108]
Collecting python-gssapi==0.6.4
  Downloading http://mirrors.aliyun.com/pypi/packages/a4/9e/648b4e85235097edcee561c986f7075cb1606be24c514cfcdd2930e35c5e/python-gssapi-0.6.4.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/py3/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-szkdyeur/python-gssapi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-szkdyeur/python-gssapi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-szkdyeur/python-gssapi/pip-egg-info
         cwd: /tmp/pip-install-szkdyeur/python-gssapi/
    Complete output (33 lines):
    WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
    ERROR: Could not find a version that satisfies the requirement pyasn1>=0.1.2 (from versions: none)
    ERROR: No matching distribution found for pyasn1>=0.1.2
    Traceback (most recent call last):
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/opt/py3/bin/python3.6', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpbm0avmf3', '--quiet', '--index-url', 'http://mirrors.aliyun.com/pypi/simple/', 'pyasn1>=0.1.2']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-szkdyeur/python-gssapi/setup.py", line 74, in <module>
        url="https://github.com/sigmaris/python-gssapi",
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/py3/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
        replace_conflicting=replace_conflicting
      File "/opt/py3/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/opt/py3/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/opt/py3/lib64/python3.6/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/opt/py3/bin/python3.6', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpbm0avmf3', '--quiet', '--index-url', 'http://mirrors.aliyun.com/pypi/simple/', 'pyasn1>=0.1.2']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by wojiushixiaobai** [comment]
@lyric2018 换个pip源，关键错误如下
```
ERROR: Could not find a version that satisfies the requirement pyasn1>=0.1.2 (from versions: none)
ERROR: No matching distribution found for pyasn1>=0.1.2
```
