### ISSUE TITLE
批量命令执行报错提示：Error occur: SoftTimeLimitExceeded()

### ISSUE THREAD

**Issue by Almira2020** [jumpserver/docs#140]
报错信息：
$ sleep 61 (2020-05-14 15:34:55) *****************************************************************************************************************************************
Error occur: SoftTimeLimitExceeded()
---------- 任务结束 ----------
--- Logging error ---
Traceback (most recent call last):
File "/usr/lib64/python3.6/logging/__init__.py", line 998, in emit
    self.flush()
File "/usr/lib64/python3.6/logging/__init__.py", line 978, in flush
    self.stream.flush()
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
File "/opt/py3/bin/celery", line 10, in <module>
    sys.exit(main())
File "/opt/py3/lib64/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
File "/opt/py3/lib64/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
File "/opt/py3/lib64/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
File "/opt/py3/lib64/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
File "/opt/py3/lib64/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
File "/opt/py3/lib64/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
File "/opt/py3/lib64/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
File "/opt/py3/lib64/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
File "/opt/py3/lib64/python3.6/site-packages/celery/bin/worker.py", line 256, in run
    worker.start()
File "/opt/py3/lib64/python3.6/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
File "/opt/py3/lib64/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
File "/opt/py3/lib64/python3.6/site-packages/celery/bootsteps.py", line 370, in start
    return self.obj.start()
File "/opt/py3/lib64/python3.6/site-packages/celery/worker/consumer/consumer.py", line 320, in start
    blueprint.start(self)
File "/opt/py3/lib64/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
File "/opt/py3/lib64/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
File "/opt/py3/lib64/python3.6/site-packages/celery/worker/loops.py", line 88, in asynloop
    next(loop)
File "/opt/py3/lib64/python3.6/site-packages/kombu/async/hub.py", line 345, in create_loop
    cb(*cbargs)
File "/opt/py3/lib64/python3.6/site-packages/celery/concurrency/asynpool.py", line 444, in _event_process_exit
    self.maintain_pool()
File "/opt/py3/lib64/python3.6/site-packages/billiard/pool.py", line 1307, in maintain_pool
    self._maintain_pool()
File "/opt/py3/lib64/python3.6/site-packages/billiard/pool.py", line 1299, in _maintain_pool
    self._repopulate_pool(joined)
File "/opt/py3/lib64/python3.6/site-packages/billiard/pool.py", line 1284, in _repopulate_pool
    self._create_worker_process(self._avail_index())
File "/opt/py3/lib64/python3.6/site-packages/celery/concurrency/asynpool.py", line 439, in _create_worker_process
    return super(AsynPool, self)._create_worker_process(i)
File "/opt/py3/lib64/python3.6/site-packages/billiard/pool.py", line 1116, in _create_worker_process
    w.start()
File "/opt/py3/lib64/python3.6/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
File "/opt/py3/lib64/python3.6/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
File "/opt/py3/lib64/python3.6/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
File "/opt/py3/lib64/python3.6/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
File "/opt/py3/lib64/python3.6/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
File "/opt/py3/lib64/python3.6/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
File "/opt/py3/lib64/python3.6/site-packages/billiard/pool.py", line 289, in __call__
    sys.exit(self.workloop(pid=pid))
File "/opt/py3/lib64/python3.6/site-packages/billiard/pool.py", line 358, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
File "/opt/py3/lib64/python3.6/site-packages/celery/app/trace.py", line 537, in _fast_trace_task
    uuid, args, kwargs, request,
File "/opt/py3/lib64/python3.6/site-packages/celery/app/trace.py", line 448, in trace_task
    'return_value': Rstr, 'runtime': T,
File "/opt/py3/lib64/python3.6/site-packages/celery/app/trace.py", line 123, in info
    logger.info(fmt, context, extra={'data': context})
Message: 'Task %(name)s[%(id)s] succeeded in %(runtime)ss: %(return_value)s'
Arguments: {'id': 'c6339447-049b-4230-94c1-df43e5aa3c66', 'name': 'ops.tasks.run_command_execution', 'return_value': 'None', 'runtime': 60.04014527797699

系统版本：Version 1.5.3-2 GPLv2.

**Comment by wojiushixiaobai** [comment]
请使用最新版本，旧版本的问题我们会在新版本中修复
