### ISSUE TITLE
正常安装1.4.8版本报错

### ISSUE THREAD

**Issue by 17634369935** [jumpserver/docs#46]
django.db.utils.OperationalError: (1050, "Table 'django_celery_beat_crontabschedule' already exists")
Collect static files
Collect static file done

- Start Celery as Distributed Task Queue

- Start Beat as Periodic Task Scheduler
Error: beat start error
Stop service: gunicorn
Stop service: celery
beat is stopped

一直报这个错，不知道怎么处理？

1.5.2版本也报这个错，到底是什么原因啊？

**Comment by 17634369935** [comment]
求大神解答

**Comment by lwx2615** [comment]
Jumpserver version 1.5.3安装启动也报错。
SyntaxError: invalid syntax
Check database connection ...
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/py3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/py3/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/py3/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3/lib/python3.7/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/opt/py3/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/jumpserver/apps/ops/__init__.py", line 1, in <module>
    from .celery import app as celery_app
  File "/opt/jumpserver/apps/ops/celery/__init__.py", line 5, in <module>
    from kombu import Exchange, Queue
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/opt/py3/lib/python3.7/site-packages/kombu/__init__.py", line 81, in __getattr__
    module = __import__(object_origins[name], None, None, [name])
  File "/opt/py3/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
    from .abstract import MaybeChannelBound, Object
  File "/opt/py3/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
    from .connection import maybe_channel
  File "/opt/py3/lib/python3.7/site-packages/kombu/connection.py", line 893
    return self.transport.implements.async

**Comment by wojiushixiaobai** [comment]
@17634369935 请用全新的数据库
@lwx2615 请仔细参考官方文档，没有任何地方说明支持python3.7，必须是python3.6
